warp:
  image: caomingjun/warp
  container_name: warp
  restart: always
  devices:
    - /dev/net/tun:/dev/net/tun
  ports:
    - '1080:1080'
  environment:
    - WARP_SLEEP=2
    # Below is optional but HIGHLY recommended
    - WARP_LICENSE_KEY=YOUR LICENSE KEY HERE
  cap_add:
    - NET_ADMIN
  sysctls:
    - net.ipv6.conf.all.disable_ipv6=0
    - net.ipv4.conf.all.src_valid_mark=1
  volumes:
    - ./data:/var/lib/cloudflare-warp